# -*- coding: utf-8 -*-
"""sea_level_predictor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvqYWmym4Ds5DcwOPXB8NKIVy807cKxL
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress


def draw_plot():
    # Load data
    df = pd.read_csv("epa-sea-level.csv")

    # Create scatter plot
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.scatter(df["Year"], df["CSIRO Adjusted Sea Level"], color="blue", label="Data")

    # -----------------------------
    # Line of best fit (ALL data)
    # -----------------------------
    slope, intercept, r_value, p_value, std_err = linregress(
        df["Year"], df["CSIRO Adjusted Sea Level"]
    )

    years_extended = pd.Series(range(df["Year"].min(), 2051))
    ax.plot(
        years_extended,
        intercept + slope * years_extended,
        "r",
        label="Best Fit (All Data)"
    )

    # -----------------------------
    # Line of best fit (2000+)
    # -----------------------------
    df_2000 = df[df["Year"] >= 2000]

    slope2, intercept2, r2, p2, se2 = linregress(
        df_2000["Year"], df_2000["CSIRO Adjusted Sea Level"]
    )

    years_extended_2 = pd.Series(range(2000, 2051))
    ax.plot(
        years_extended_2,
        intercept2 + slope2 * years_extended_2,
        "green",
        label="Best Fit (2000+)"
    )

    # Labels and title
    ax.set_xlabel("Year")
    ax.set_ylabel("Sea Level (inches)")
    ax.set_title("Rise in Sea Level")

    return fig
    from sea_level_predictor import draw_plot
import matplotlib.pyplot as plt

draw_plot()
plt.show()

import requests

url = "https://raw.githubusercontent.com/freeCodeCamp/boilerplate-sea-level-predictor/master/epa-sea-level.csv"

with open("epa-sea-level.csv", "wb") as f:
    f.write(requests.get(url).content)

print("Downloaded dataset")